version: '2'

services:
  web:

    image: madderle/data-python-stack:latest
    container_name: djangoweb_01
    command: /bin/sh -c 'cd Model-Deployment && gunicorn -b:8000 deploy_models.wsgi:application -w 2'

    volumes:
      - ./src:/home/ds
    ports:
      - "8000:8000"
      - "8888:8888"
    expose:
      - "8000"
      - "8888"
